# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Socketchat-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Socketchat-ios

  target 'Socketchat-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Socketchat-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'IQKeyboardManager'
  pod 'Socket.IO-Client-Swift'

end
